### ISSUE TITLE
[Feature Request] - Optional notifications for expiring warranties

### ISSUE THREAD

**Issue by exe-r** [sassanix/Warracker#1]
First, I like the project, nice idea. One nice feature I would be interested in is integration with other notification services to notify if X period is approaching for an item to have expired warranty. 

Thanks!

**Comment by sassanix** [comment]
In the latest update, I've added the email notifications. 

You will have to edit the docker compose file to add your email information.

**Comment by sassanix** [comment]
Here is the latest docker-compose that you can use:
```

  services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    ports:
      - "8005:80"
    volumes:
      - warracker_uploads:/data/uploads
    environment:
      - DB_HOST=warrackerdb
      - DB_NAME=warranty_db
      - DB_USER=warranty_user
      - DB_PASSWORD=${DB_PASSWORD:-warranty_password}
      - SMTP_HOST=smtp.email.com
      - SMTP_PORT=465
      - SMTP_USERNAME=youremail@email.com
      - SMTP_PASSWORD=password
    depends_on:
      warrackerdb:
        condition: service_healthy
    restart: unless-stopped
  
  warrackerdb:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=warranty_db
      - POSTGRES_USER=warranty_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-warranty_password}
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  warracker_uploads:
```
