### ISSUE TITLE
arm64 docker release

### ISSUE THREAD

**Issue by albertopasqualetto** [sassanix/Warracker#15]
Title

**Comment by sassanix** [comment]
Try again with the latest update, and let me know if it works.

**Comment by albertopasqualetto** [comment]
Hello, didn't see the answer. What did you change? It seems not working on my end.

**Comment by sassanix** [comment]
> Hello @sassanix , didn't see the answer. What did you change? It seems not working on my end.

Hello, another user mentioned they got it working on arm64 with the latest release. I updated the python and Debian. 

The image should now support arm64 processors. 

You can also force it by using this in your docker-compose. 

services:
  warracker:
    platform: linux/arm64
    ...
  
  warrackerdb:
    platform: linux/arm64
    ...

Please let me know if that works for you.

**Comment by albertopasqualetto** [comment]
I still get `Error response from daemon: image with reference ghcr.io/sassanix/warracker/main:latest was found but its platform (linux/amd64) does not match the specified platform (linux/arm64)`

The point is not the Dockerfile. Probably it supports arm64, but it should be _built_ for arm64 and I don't see multi-arch tags here `https://github.com/sassanix/Warracker/pkgs/container/warracker%2Fmain/412818567?tag=0.9.9.6`

**Comment by sassanix** [comment]
> I still get `Error response from daemon: image with reference ghcr.io/sassanix/warracker/main:latest was found but its platform (linux/amd64) does not match the specified platform (linux/arm64)`
> 
> The point is not the Dockerfile. Probably it supports arm64, but it should be _built_ for arm64 and I don't see multi-arch tags here `https://github.com/sassanix/Warracker/pkgs/container/warracker%2Fmain/412818567?tag=0.9.9.6`

I'll work on this, it's a priority to get it working, thank you for being patient with me 🙏

**Comment by icywhisker-official** [comment]
At this time, you must use docker compose to build the app for arm64. You cannot utilize the docker run command to automatically pull the image from GitHub. It does not exist. Follow the instructions regarding the docker compose script.

**Comment by icywhisker-official** [comment]
THIS IS UNTESTED CODE.

You can try this and it should be a one shot build command that gets the docker up immediately. 

No sudo needed

mkdir -p ~/tmp && cd ~/tmp && git clone https://github.com/sassanix/Warracker.git && cd Warracker && docker compose build && docker compose up -d

**Comment by albertopasqualetto** [comment]
@icywhisker-official building on my side will make it surely. But that is not the solution.

**Comment by albertopasqualetto** [comment]
> > I still get `Error response from daemon: image with reference ghcr.io/sassanix/warracker/main:latest was found but its platform (linux/amd64) does not match the specified platform (linux/arm64)`
> > 
> > The point is not the Dockerfile. Probably it supports arm64, but it should be _built_ for arm64 and I don't see multi-arch tags here `https://github.com/sassanix/Warracker/pkgs/container/warracker%2Fmain/412818567?tag=0.9.9.6`
> 
> I'll work on this, it's a priority to get it working, thank you for being patient with me 🙏

Thanks!

**Comment by sassanix** [comment]
I'm going to do my best to have all the updates including the arm64 released on 0.9.9.7, thank you again for being so patient.

**Comment by sassanix** [comment]
Can you test the arm64 version as a test and let me know if it works?

Once it's all confirmed, the main release will have arm64 support.

Here is the docker-compose for you to try with the arm64test image

```
services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:arm64test
    ports:
      - "8005:80"
    volumes:
      - warracker_uploads:/data/uploads
    environment:
      - DB_HOST=warrackerdb
      - DB_NAME=warranty_db
      - DB_USER=warranty_user
      - DB_PASSWORD=${DB_PASSWORD:-warranty_password}
      - SMTP_HOST=smtp.email.com
      - SMTP_PORT=465
      - SMTP_USERNAME=youremail@email.com
      - SMTP_PASSWORD=password
      - SECRET_KEY=${APP_SECRET_KEY:-your_strong_default_secret_key_here} 
      - MAX_UPLOAD_MB=32 # Example: Set max upload size to 32MB 
      - NGINX_MAX_BODY_SIZE_VALUE=32M # For Nginx, ensure this matches MAX_UPLOAD_MB in concept (e.g., 32M)
    # - FLASK_DEBUG=0
    depends_on:
      warrackerdb:
        condition: service_healthy
    restart: unless-stopped
  
  warrackerdb:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=warranty_db
      - POSTGRES_USER=warranty_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-warranty_password}
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  warracker_uploads:
```
