### ISSUE TITLE
ERROR when adding item

### ISSUE THREAD

**Issue by Node815** [sassanix/Warracker#22]
When I try to add my first warranty item, it errors out with this error in the logs

![Image](https://github.com/user-attachments/assets/c8e6eb85-fd61-432f-9da6-2a78db200b08)

I can add everything else in the dialog fine but when I tell it to save the warranty it records and error.

Additionally,   I can't tell you how many times, I lost my entry because I lost exited the dialog by tabbing out to get my serial numbers etc only to see that it didn't save.  It only saves until you get to the end.  Would it be possible to have it save when the user clicks 'next'  instead?

**Comment by sassanix** [comment]
Hi Node815, 

Try the test image, it's the latest version. Please let me know if it works for you.

It has a lot of QOL and other fixes included, it's a release candidate for the upcoming release. 

    image: ghcr.io/sassanix/warracker/test:9.9.2rc 

If it works, then once I release the new version, switch the image to the main latest version.

**Comment by Node815** [comment]
Still not working.  

![Image](https://github.com/user-attachments/assets/b2e79e88-c4d8-4a92-b434-b5fcf8b6dcab)

I'm not sure if it's  the lifetime error in the message column timezone does not exist is what is causing this.    This is my compose file:

```
services:
  warracker:
    image: ghcr.io/sassanix/warracker/test:9.9.2rc 
    ports:
      - "8005:80"
    volumes:
      - /mnt/appdata/warracker/uploads:/data/uploads
    environment:
      - DB_HOST=warrackerdb
      - DB_NAME=warranty_db
      - DB_USER=warranty
      - DB_PASSWORD=${DB_PASSWORD:-warranty_password}
      - SMTP_HOST=wednesday.mxrouting.net
      - SMTP_PORT=465
      - SMTP_USERNAME=redacted@redacted.com
      - SMTP_PASSWORD=FANCYPASSWORD
    depends_on:
      warrackerdb:
        condition: service_healthy
    restart: unless-stopped
```
The .env file:

```
# Database configuration
DB_PASSWORD=gakxb993J&DeAhQ*Co
DB_ADMIN_PASSWORD=f4!NpC@iM*H7UgzDOd

# Email configuration
#SMTP_HOST=localhost
#SMTP_PORT=1025
#SMTP_USERNAME=youremail@email.com
#SMTP_PASSWORD=your_smtp_password
```

I didn't see the point of repeating that in the .env so I just commented that out.   Should we be adding a TZ environment variable?  I took this compose from your README under the **PULL DOCKER** header.

**UPDATE**

I added the Timezone in my environment and that error went away with the missing timezone, but now:

![Image](https://github.com/user-attachments/assets/22f7878e-f8ce-44c3-9e08-6936e99747be)

**ODDLY ENOUGH**  (this is getting weird)  A new error showed up upon trying again:

> INFO:app:New invoice uploaded: uploads/20250419193530_Pscontrollers.jpg
> ERROR:app:Error adding warranty: column "is_lifetime" of relation "warranties" does not exist
> LINE 4: ...anual_path, product_url, purchase_price, user_id, is_lifetim...
>                                                              ^


I didn't add a product URL as it's not needed.
