### ISSUE TITLE
Possibility of pushing image to docker hub ?

### ISSUE THREAD

**Issue by Denzil-Briffa** [sassanix/Warracker#4]
Any chance that the image would be built and pushed to docker hub to facilitate pulling of image for people using it through helm charts or any automated systems ?

**Comment by EweSparky** [comment]
Or GHCR or some other registry if not Docker Hub.

**Comment by sassanix** [comment]
> Any chance that the image would be built and pushed to docker hub to facilitate pulling of image for people using it through helm charts or any automated systems ?

Definitely, as I work on it more, I'll have it available on docker hub or alternatives with a docker compose.

**Comment by sassanix** [comment]
Use the following Docker Compose configuration to deploy the latest build of the image:

```yaml
version: '3'

services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    ports:
      - "8005:80"
    volumes:
      - ./uploads:/data/uploads
    environment:
      - DB_HOST=warrackerdb
      - DB_NAME=warranty_db
      - DB_USER=warranty_user
      - DB_PASSWORD=${DB_PASSWORD:-warranty_password}
    depends_on:
      warrackerdb:
        condition: service_healthy
    restart: unless-stopped

  warrackerdb:
    image: "postgres:15-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=warranty_db
      - POSTGRES_USER=warranty_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-warranty_password}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warranty_user -d warranty_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
```

**Comment by Green-Kite** [comment]
@sassanix thx for the new compose file. Tried it right now but got an `unauthorized`  error when trying to pull.

**Comment by sassanix** [comment]
> @sassanix thx for the new compose file. Tried it right now but got an `unauthorized`  error when trying to pull.

You're welcome, I'll work on it. See if you put 0.5.0 instead of latest fixes it.

**Comment by Green-Kite** [comment]
> > [@sassanix](https://github.com/sassanix) thx for the new compose file. Tried it right now but got an `unauthorized`  error when trying to pull.
> 
> You're welcome, I'll work on it. See if you put 0.5.0 instead of latest fixes it.

Sadly it does not.
`Error response from daemon: Head "https://ghcr.io/v2/sassanix/warracker/main/manifests/0.5.0": unauthorised`

**Comment by sassanix** [comment]
> > > [@sassanix](https://github.com/sassanix) thx for the new compose file. Tried it right now but got an `unauthorized`  error when trying to pull.
> > 
> > You're welcome, I'll work on it. See if you put 0.5.0 instead of latest fixes it.
> 
> Sadly it does not.
> `Error response from daemon: Head "https://ghcr.io/v2/sassanix/warracker/main/manifests/0.5.0": unauthorised`

Alright I'm going to see why my push isn't working. Sorry for the inconvenience!

**Comment by sassanix** [comment]
> > > [@sassanix](https://github.com/sassanix) thx for the new compose file. Tried it right now but got an `unauthorized`  error when trying to pull.
> > 
> > 
> > You're welcome, I'll work on it. See if you put 0.5.0 instead of latest fixes it.
> 
> Sadly it does not. `Error response from daemon: Head "https://ghcr.io/v2/sassanix/warracker/main/manifests/0.5.0": unauthorised`

I finally figured out what I was missing, I had to also make the repo public within the GitHub packages :) 

Give it a try, and let me know :)

**Comment by Green-Kite** [comment]
I was able to pull it, but loading the page show me an database error: Failed to load warranties

**Comment by sassanix** [comment]
Can you give me the logs as well? 

I'll see what's going on

**Comment by sassanix** [comment]
I figured what's happening, the init.sql is missing, I need to work on the docker file to have it create it if it's missing.

The workaround around is for you to create a folder and copy the init.sql manually and map it through the docker compose:

postgres_data:/var/lib/postgresql/


I'll work on it, and let you know as soon as I can, thanks again for letting me know about the issues :)


```
version: '3'

services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    ports:
      - "8005:80"
    volumes:
      - ./uploads:/data/uploads
    environment:
      - DB_HOST=warrackerdb
      - DB_NAME=warranty_db
      - DB_USER=warranty_user
      - DB_PASSWORD=${DB_PASSWORD:-warranty_password}
    depends_on:
      warrackerdb:
        condition: service_healthy
    restart: unless-stopped

  warrackerdb:
    build: ./postgres  # Use the custom-built Postgres image
    environment:
      - POSTGRES_DB=warranty_db
      - POSTGRES_USER=warranty_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-warranty_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warranty_user -d warranty_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
```

**Comment by sassanix** [comment]
@Green-Kite 

**Summary**

Here's a working temporary Docker Compose configuration that has been tested. The database creation via `Dockerfile` is still in progress. This thread will remain open for any issues related to the Docker Compose file, and I will provide updates.

---

📝 **Details**

Here's a temporary working Docker Compose configuration for you. It has been tested and confirmed to be functional, both with Portainer and through standard methods.

```
services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    ports:
      - "8005:80"
    volumes:
      - warracker_uploads:/data/uploads
    environment:
      - DB_HOST=warrackerdb
      - DB_NAME=warranty_db
      - DB_USER=warranty_user
      - DB_PASSWORD=${DB_PASSWORD:-warranty_password}
    depends_on:
      - warrackerdb
    restart: unless-stopped

  # Use a standard PostgreSQL image with initialization
  warrackerdb:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=warranty_db
      - POSTGRES_USER=warranty_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-warranty_password}
      # This will create the init script directly
      - POSTGRES_MULTIPLE_DATABASES=warranty_db
      - PGUSER=warranty_user
    restart: unless-stopped
    # Simple initialization approach
    command: >
      sh -c '
        # Create initialization script
        mkdir -p /docker-entrypoint-initdb.d
        echo "CREATE TABLE IF NOT EXISTS warranties (
          id SERIAL PRIMARY KEY,
          product_name VARCHAR(255) NOT NULL,
          product_url TEXT,
          purchase_date DATE NOT NULL,
          warranty_years INTEGER NOT NULL,
          expiration_date DATE NOT NULL,
          invoice_path TEXT,
          manual_path TEXT,
          purchase_price DECIMAL(10, 2)
        );" > /docker-entrypoint-initdb.d/01-tables.sql
        
        echo "CREATE TABLE IF NOT EXISTS serial_numbers (
          id SERIAL PRIMARY KEY,
          warranty_id INTEGER REFERENCES warranties(id) ON DELETE CASCADE,
          serial_number VARCHAR(255) NOT NULL
        );" > /docker-entrypoint-initdb.d/02-serial-numbers.sql
        
        echo "CREATE INDEX IF NOT EXISTS idx_warranty_id ON serial_numbers(warranty_id);
        CREATE INDEX IF NOT EXISTS idx_expiration_date ON warranties(expiration_date);" > /docker-entrypoint-initdb.d/03-indexes.sql
        
        # Run the standard PostgreSQL entrypoint script
        docker-entrypoint.sh postgres
      '

volumes:
  postgres_data:
  warracker_uploads:
```

🚧 **Next Steps**

*   I am currently refining the `Dockerfile` to enable database building through it. This will ensure that newer fields are correctly updated.
*   I will post a smaller Docker Compose configuration.

💬 **Ongoing Support**

*   This thread will remain open for any issues encountered with this temporary Docker Compose setup.
*   I will keep everyone informed about the progress.

**Comment by sassanix** [comment]
I'm working on an update to this, as the latest update adds timezones and email notifications and other QOL changes.

Thank you for being patient with me :)

**Comment by sassanix** [comment]
I've added the environment for the email notifications, please make sure to add your email address information afor the notifications to work.

**Comment by sassanix** [comment]
Here is the updated docker-compose for you to use in your stacks:


 ```
 services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    ports:
      - "8005:80"
    volumes:
      - warracker_uploads:/data/uploads
    environment:
      - DB_HOST=warrackerdb
      - DB_NAME=warranty_db
      - DB_USER=warranty_user
      - DB_PASSWORD=${DB_PASSWORD:-warranty_password}
      - SMTP_HOST=smtp.email.com
      - SMTP_PORT=465
      - SMTP_USERNAME=youremail@email.com
      - SMTP_PASSWORD=password
    depends_on:
      warrackerdb:
        condition: service_healthy
    restart: unless-stopped
  
  warrackerdb:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=warranty_db
      - POSTGRES_USER=warranty_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-warranty_password}
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  warracker_uploads:
```
