### ISSUE TITLE
Still getting database errors about admin and I can not create a user

### ISSUE THREAD

**Issue by Morethanevil** [sassanix/Warracker#80]
Hi, thanks for Warracker!

I tried the new beta, because it should not need admin privileges anymore. I am using a postgres database from my host, which I created before starting Warracker like this:

```sql
CREATE USER warracker WITH PASSWORD 'strongpassword';
CREATE DATABASE warrackerdb WITH OWNER warracker ENCODING 'utf8' TEMPLATE template0;
```

After starting the container the log looks like this:

[warracker.txt](https://github.com/user-attachments/files/20753807/warracker.txt)

The container starts anyway successfully, but I can not create a user. 

```bash
warracker  | INFO:backend.notifications:Retrying database connection in 2 seconds...
warracker  | WARNING:backend.notifications:Database connection attempt 2 failed: server closed the connection unexpectedly
warracker  |    This probably means the server terminated abnormally
warracker  |    before or while processing the request.
warracker  |
warracker  | INFO:backend.notifications:Retrying database connection in 2 seconds...
warracker  | ERROR:backend.notifications:Error determining notification eligibility: FEHLER:  Spalte up.timezone existiert nicht
warracker  | LINE 2: ....id, u.email, u.first_name, up.notification_time, up.timezon...
warracker  |                                                              ^
warracker  |
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 08:50:13 UTC)" executed successfully
warracker  | ERROR:backend.notifications:Error determining notification eligibility: FEHLER:  Spalte up.timezone existiert nicht
warracker  | LINE 2: ....id, u.email, u.first_name, up.notification_time, up.timezon...
warracker  |                                                              ^
warracker  |
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 08:50:13 UTC)" executed successfully
warracker  | ERROR:backend.notifications:Error determining notification eligibility: FEHLER:  Spalte up.timezone existiert nicht
warracker  | LINE 2: ....id, u.email, u.first_name, up.notification_time, up.timezon...
warracker  |                                                              ^
warracker  |
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 08:50:13 UTC)" executed successfully
warracker  | ERROR:backend.notifications:Error determining notification eligibility: FEHLER:  Spalte up.timezone existiert nicht
warracker  | LINE 2: ....id, u.email, u.first_name, up.notification_time, up.timezon...
warracker  |                                                              ^
warracker  |
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 08:50:13 UTC)" executed successfully
warracker  | ERROR:backend.oidc_handler:[OIDC_HANDLER] Error fetching OIDC status: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT key, value FROM site_settings WHERE key IN ('oidc_ena...
warracker  |                                ^
warracker  |
warracker  | ERROR:app:Registration error: FEHLER:  Spalte »is_owner« von Relation »users« existiert nicht
warracker  | LINE 1: ..., password_hash, first_name, last_name, is_admin, is_owner) ...
warracker  |                                                              ^
warracker  |
```

My compose.yaml:

```yaml
services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    container_name: warracker
#    ports:
#      - "8005:80"
    networks:
      innendienst:
        ipv4_address: 172.20.0.71
        ipv6_address: fd00:112::71
    volumes:
      - /docker/warracker/uploads:/data/uploads
      - /var/run/postgresql:/var/run/postgresql
    environment:
       DB_HOST: ${DB_HOST}
       DB_NAME: ${DB_NAME}
       DB_USER: ${DB_USER}
       DB_PASSWORD: ${DB_PASSWORD}
       SMTP_HOST: ${SMTP_HOST}
       SMTP_PORT: 465
       SMTP_USERNAME: ${SMTP_USERNAME}
       SMTP_PASSWORD: ${SMTP_PASSWORD}
       SECRET_KEY: ${SECRET_KEY}
       MAX_UPLOAD_MB: 50 # Example: Set max upload size to 32MB
       NGINX_MAX_BODY_SIZE_VALUE: 50M # For Nginx, ensure this matches MAX_UPLOAD_MB in concept (e.g., 32M)

      # OIDC SSO Configuration (User needs to set these based on their OIDC provider)
       OIDC_PROVIDER_NAME: Authentik
       OIDC_CLIENT_ID: ${OIDC_CLIENT_ID} # e.g., your_oidc_client_id_from_provider
       OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET} # e.g., your_oidc_client_secret_from_provider
       OIDC_ISSUER_URL: ${OIDC_ISSUER_URL} # e.g., https://your-oidc-provider.com/auth/realms/your-realm
       OIDC_SCOPE: ${OIDC_SCOPE}

      # URL settings (Important for OIDC redirects and email links)
      # Ensure these point to the public-facing URL of your application

       FRONTEND_URL: ${FRONTEND_URL}
       APP_BASE_URL: ${APP_BASE_URL}

      # Apprise notifications

       APPRISE_ENABLED: true # Enable/disable Apprise notifications
       APPRISE_URLS: ${APPRISE_URLS} # Comma-separated list of notification URLs (e.g., "mailto://user:pass@gmail.com,discord://webhook_id/webhook_token")
       APPRISE_EXPIRATION_DAYS: 30 # Days before expiration to send notifications (comma-separated)
       APPRISE_NOTIFICATION_TIME: 14:00 # Time of day to send notifications (HH:MM format)
       APPRISE_TITLE_PREFIX: Warracker # Prefix for notification titles

      # Memory optimization settings
       WARRACKER_MEMORY_MODE: ${WARRACKER_MEMORY_MODE} # Options: optimized (default), ultra-light

    restart: always
networks:
  innendienst:
    external: true

```
Seems like Warracker still wants admin :(

**Comment by sassanix** [comment]
Hi @Morethanevil , looking at your docker compose now.


```
networks:
  innendienst:
    external: true
```

Ensure:

- The external PostgreSQL server is accessible from this Docker network.
- If it's another container, it must be attached to the same innendienst network.
- If it's a host-level service, its IP (like 172.20.0.10) must be reachable from inside the container.

Assuming your external postgresql is at 172.20.0.10 try this working example for the docker compose:


```
services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    container_name: warracker
    ports:
      - "8005:80"
    networks:
      innendienst:
        ipv4_address: 172.20.0.71
        ipv6_address: fd00:112::71
    volumes:
      - /docker/warracker/uploads:/data/uploads
    environment:
      DB_HOST: 172.20.0.10
      DB_NAME: warranty_db
      DB_USER: warranty_user
      DB_PASSWORD: your_password
      SMTP_HOST: smtp.email.com
      SMTP_PORT: 465
      SMTP_USERNAME: youremail@email.com
      SMTP_PASSWORD: password
      SECRET_KEY: your_strong_secret_key
      MAX_UPLOAD_MB: 50
      NGINX_MAX_BODY_SIZE_VALUE: 50M
      OIDC_PROVIDER_NAME: Authentik
      OIDC_CLIENT_ID: your_oidc_client_id
      OIDC_CLIENT_SECRET: your_oidc_client_secret
      OIDC_ISSUER_URL: https://your-oidc-provider.com/realm
      OIDC_SCOPE: openid email profile
      FRONTEND_URL: http://your.domain.com
      APP_BASE_URL: http://your.domain.com
      APPRISE_ENABLED: true
      APPRISE_URLS: your_apprise_urls
      APPRISE_EXPIRATION_DAYS: 30
      APPRISE_NOTIFICATION_TIME: 14:00
      APPRISE_TITLE_PREFIX: Warracker
      WARRACKER_MEMORY_MODE: optimized
    restart: always

networks:
  innendienst:
    external: true
```
